### ISSUE TITLE
Check possible wrong description

### ISSUE THREAD

**Issue by cesariocanhao** [cryptonote-social/csminer#1]
In your readme you have the following regarding Macs:

_Power napping should be disabled to ensure the miner isn't suspended while the screen is locked._

But shouldn't it be the opposite? Shouldn't be power nap be enabled?

In Power nap description it says: _While sleeping, your Mac can backup using Time Machine and periodically check for new email, calendar, and other iCloud updates._

**Comment by cryptonote-social** [comment]
Hmm, I guess the important thing is that sleeping is disabled when display is off, not so much the power nap setting.  I suspect power nap whether on or off will not allow the miner to run the moment the machine sleeps.

**Comment by cesariocanhao** [comment]
So basically the option that matters is the _Put hard disks to sleep when possible_? Apple's user friendly nomenclature is easier to understand to non-technical users, but sometimes it can get a bit in the way for more technical stuff :)

**Comment by cryptonote-social** [comment]
I think it's fine for drives to sleep, but the computer itself needs to stay awake. In Energy Settings, I think you just need to make sure "Prevent computer from sleeping automatically when the display is off" is checked, and the others should be irrelevant. I'll do some testing to confirm. Thanks for bringing this to my attention.

**Comment by cryptonote-social** [comment]
Fixed in https://github.com/cryptonote-social/csminer/commit/562af181291349d4f01a8f6fad73556641f49a1f
