### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by bay1ts** [cryptonote-social/csminer#7]
/root/go/pkg/mod/github.com/cryptonote-social/csminer@v0.3.2-linux/rx/rx.go:11:11: fatal error: rxlib.h: No such file or directory
   11 |  #include "rxlib.h"
      |           ^~~~~~~~~

**Comment by cryptonote-social** [comment]
You figure it out? the rxlib is in my fork of RandomX.  I apologize my build instructions are inadequate!

**Comment by sikhaman** [comment]
I have same problem here on mac with m3 chip. any ideas how to fix?
