### ISSUE TITLE
Is it just me or the ZIP file of csminer for Windows is broken?

### ISSUE THREAD

**Issue by forkthat** [cryptonote-social/csminer#9]
![image](https://user-images.githubusercontent.com/63246612/127739993-0d934d49-76c8-4cbc-b0c6-8d24195a5df0.png)

I try to extract it on my computer but it shows this on the folder. I tried to download the file from the website multiple times and the same result.

![image](https://user-images.githubusercontent.com/63246612/127740055-b7528381-36e6-4dfb-9402-9fa01a35d9c8.png)

I tried to extract the linux version and it was okay.
Thank you.

**Comment by cryptonote-social** [comment]
Hmm, it does look messed up doesn't it?  looking into it....

**Comment by cryptonote-social** [comment]
Yup looks like I somehow copied the wrong file. I've updated it now. Try again?  Make sure you hit ctrl-Reload (or F5) on the download page first to make sure you don't download a cached version.  File size should be 2849925. Thank you for the report!

**Comment by forkthat** [comment]
Thank you very much! It is fixed now.
However I must say, the performance on WIndows is atrocious (only 50% hashrate of what I get on Linux). Hahaha! Maybe I should reinstall Linux on my computer.
Thank you again.

**Comment by cryptonote-social** [comment]
Check to see if hugepages is enabled? It should perform about the same as long as it can allocate hugepages. With Windows that usually requires you jump through a few hoops to enable it though....

**Comment by forkthat** [comment]
I checked the XMRig Documentation on how to enable hugepages however it was evident that I need to have Windows 10 Professional, Ultimate, or Server editions.  I only have the Home edition so back to Linux I guess...  Thanks for your time and have a great day.

**Comment by cryptonote-social** [comment]
[](No winhome supports hugepages, it's just a bit more of a pain to set up. You need to activate gpedit: 

https://www.itechtics.com/enable-gpedit-windows-10-home/

And then you can activate as described here (only for your own user account rather than sql server service account):

https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-the-lock-pages-in-memory-option-windows?view=sql-server-ver15
